version: '2'
services:
  smartlampweb-app:
    image: smartlampweb
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://smartlampweb-mariadb:3306/smartlampweb?useLegacyDatetimeCode=false&serverTimezone=UTC
      - JHIPSTER_SLEEP=120 # gives time for mariadb server to start
    ports:
      - 8080:8080
  smartlampweb-mariadb:
    extends:
      file: mariadb.yml
      service: smartlampweb-mariadb
